# ==========================
# ### Customer Defined Values ###
# ==========================
# All values below are defined by the customer for a specific installation.
# These values must be customized according to the installation environment.
#
# Please ensure to set the appropriate values for your specific use case.
#
# System section below should **NOT** be changed, as it contains internal settings for the system.
# These settings are predefined and should not be modified by the customer.

image:
  repository: "default-repository"  # Repository where the image is stored
  name: "default-image"             # Name of the image to be used
  tag: "default-tag"                # Tag for the image
  digest: ""                        # Image digest (optional)

namespace:
  name: pan  # Kubernetes namespace where resources will be deployed

dockerPullSecret: ""  # Secret for pulling images from a private registry

distribution:
  id: "default-distribution-id"  # Retrieve distribution ID from Palo Alto Networks systems during installation
  url: "https://distributions.traps.paloaltonetworks.com"  # Retrieve distribution URL from Palo Alto Networks systems during installation

optionalValues:
  CLUSTER_URI: ""    # Cluster URI should be set when metadata service is not reachable from the cluster
  UPLOAD_LOG_LEVEL: "ERROR"  # Log level for uploading logs ("ERROR", "WARNING", "INFO", "DEBUG", "PANIC")
  CONSOLE_LOG_LEVEL: "INFO"  # Log level for console output ("ERROR", "WARNING", "INFO", "DEBUG", "PANIC")

# ==========================
# ### System Section ###
# ==========================
# The values below are predefined system settings.
# **Do not modify** these values as they are essential for the internal operation of the system.

system:
  # ==========================
  # Batch Resources
  # ==========================
  batch:
    schedule: "0 */6 * * *"  # Cron job cadence: Run every 6 hours (e.g., 0th minute of every 6th hour)
    backoffLimit: 4  # Maximum number of retries before the job is considered failed. After 4 attempts, the job will fail.

  # ==========================
  # Service Account Resources
  # ==========================
  serviceAccount:
    name: konnector-sa  # Service account name to be used by the workloads

  # ==========================
  # Config Map Resources
  # ==========================
  configMap:
    global:
      name: konnector-globals  # Name of the global configuration map

  # ==========================
  # Role Resources
  # ==========================
  roles:
    secret-creator:
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["create"]
    job-manager:
      rules:
        - apiGroups: ["batch"]
          resources: ["jobs"]
          verbs: ["get", "list", "watch", "create", "delete", "patch"]
    crds-resource-manager:
      rules:
        - apiGroups: ["panw.com"]
          resources: ["panrules"]
          verbs: ["list", "create", "patch", "get", "update", "delete", "watch"]
    connector-manager-creator:
      rules:
        - apiGroups: [""]
          resources: ["configmaps", "services"]
          verbs: ["create"]
        - apiGroups: ["apps"]
          resources: ["deployments"]
          verbs: ["create"]
        - apiGroups: ["batch"]
          resources: ["cronjobs"]
          verbs: ["create"]

  # ==========================
  # Cluster Role Resources
  # ==========================
  clusterRoles:
    cluster-manager:
      rules:
        - apiGroups: ["", "coordination.k8s.io"]
          resources: ["leases", "namespaces", "secrets", "configmaps"]
          verbs: ["get", "update", "patch", "list", "watch"]
        - apiGroups: ["admissionregistration.k8s.io"]
          resources: ["validatingwebhookconfigurations"]
          verbs: ["update", "list", "watch", "get"]
    read-inventory:
      rules:
        - apiGroups: [""]
          resources: ["namespaces", "pods", "serviceaccounts", "endpoints", "services", "configmaps", "secrets", "nodes", "nodes/proxy"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["apps"]
          resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["batch"]
          resources: ["jobs", "cronjobs"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources: ["clusterroles", "roles", "rolebindings", "clusterrolebindings"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["networkpolicies", "ingresses"]
          verbs: ["get", "list", "watch"]
    crd-manager:
      rules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["create", "get"]

  # ==========================
  # Secrets Resources
  # ==========================
  secrets:
    backendAuth:
      name: backend-auth-secret  # Secret holding backend authentication credentials (e.g. API tokens)
    dockerSecret:
      name: konnector-docker-secret  # Secret for Docker credentials (e.g., for pulling private images)
