{{- range $priority, $class := .Values.priorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ $class.name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
value: {{ $class.value }}
description: "This priority class should be used for {{ $priority }} Cortex components."
---
{{- end }}
{{- end }}
