{{- $namespace := .Values.namespace.name }}
{{- $sa := .Values.system.serviceAccount.name }}

{{- range $roleName, $roleInfo := .Values.system.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
rules:
{{- range $roleInfo.rules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName }}-binding
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- range $roleName, $roleInfo := .Values.system.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $roleName }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
rules:
{{- range $roleInfo.rules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $roleName }}-binding
  labels:
    {{- include "common.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $sa}}
    namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
