apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.system.secrets.backendAuth.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: "--set-by-konnnector-at-runtime--"
  refreshToken: "--set-by-konnnector-at-runtime--"
  sosToken: "--set-by-konnnector-at-runtime--"
  chapi: "--set-by-konnnector-at-runtime--"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.system.secrets.dockerSecret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerPullSecret | default ( "{}" | b64enc ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: distribution-id
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  distribution-id: {{ .Values.distribution.id | required "The distribution.id value is required!" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: konnector-proxy
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  httpProxy: {{ .Values.proxyValues.httpProxy | default "" | quote }}
  noProxy: {{ .Values.proxyValues.noProxy | default "" | quote }}