apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.system.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
automountServiceAccountToken: true
secrets:
 - name: {{ .Values.system.secrets.backendAuth.name }}
imagePullSecrets:
 - name: {{ .Values.system.secrets.dockerSecret.name }}
